### ISSUE TITLE
what should this do?

### ISSUE THREAD

**Issue by thecotne** [codecov/example-node#14]
https://github.com/codecov/example-node/blob/master/.travis.yml#L11
https://travis-ci.org/codecov/example-node/jobs/142818114#L141

**Comment by stevepeak** [comment]
@eddiemoore thoughts?

**Comment by eddiemoore** [comment]
Should actually remove the `--dev` and just use `npm install`. `--dev` will only install dev dependencies all down the line recursively, meaning it won't install any dependencies of your dev dependencies. Which is why things are failing.

**Comment by eddiemoore** [comment]
Adding a fix. The package deps are incorrect.

**Comment by eddiemoore** [comment]
Fixed in #15
